### ISSUE TITLE
Save joystick configurations in layout

### ISSUE THREAD

**Issue by nv-yuzho** [joshnewans/foxglove-joystick#7] opened 2024-02-16 00:33 UTC
Thank you for your work! 

I noticed that every time the Foxglove is reconnected, the settings I have for the joystick will be gone. Could we save the joystick configurations in the Foxglove layout, such as data source, publish mode, and display mode?

**Comment by joshnewans** [comment] 2024-02-16 00:53
Thanks, I'm going to close this as a duplicate of https://github.com/joshnewans/foxglove-joystick/issues/2 which should be closed by https://github.com/joshnewans/foxglove-joystick/commit/720ce8c061a57ad1ca150a53315a60ac142cdbbe but I've left it open until I've pushed the release that fixes it.

**Closed as completed by joshnewans** 2024-02-16 00:53 UTC
